//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleHttpServer.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleHttpServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;kr&quot; &gt;
        ///    &lt;head&gt;
        ///        &lt;meta charset=&quot;utf-8&quot;&gt;
        ///        &lt;title&gt;&lt;/title&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; href=&quot;style_arp.css&quot;&gt;
        ///        &lt;script src=&quot;jquery-3.4.1.min.js&quot; charset=&quot;utf-8&quot;&gt;&lt;/script&gt;
        ///        &lt;tag autocomplete=&quot;off&quot; autocorrect=&quot;off&quot; autocapitalize=&quot;off&quot; spellcheck=&quot;false&quot;/&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; href=&quot;https://use.fontawesome.com/releases/v5.6.1/css/all.css&quot;&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; href=&quot;fontawsome.css&quot;&gt; &lt;!--this enabled when it can&apos;t access fon[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string arp_frame {
            get {
                return ResourceManager.GetString("arp_frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;kr&quot; &gt;
        ///    &lt;head&gt;
        ///        &lt;meta charset=&quot;utf-8&quot;&gt;
        ///        &lt;title&gt;&lt;/title&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; href=&quot;style_dns.css&quot;&gt;
        ///        &lt;script src=&quot;jquery-3.4.1.min.js&quot; charset=&quot;utf-8&quot;&gt;&lt;/script&gt;
        ///        &lt;tag autocomplete=&quot;off&quot; autocorrect=&quot;off&quot; autocapitalize=&quot;off&quot; spellcheck=&quot;false&quot;/&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; href=&quot;https://use.fontawesome.com/releases/v5.6.1/css/all.css&quot;&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; href=&quot;fontawsome.css&quot;&gt; &lt;!--this enabled when it can&apos;t access fon[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string dns_frame {
            get {
                return ResourceManager.GetString("dns_frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;kr&quot; &gt;
        ///    &lt;head&gt;
        ///        &lt;meta charset=&quot;utf-8&quot;&gt;
        ///        &lt;title&gt;&lt;/title&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; href=&quot;style_ether.css&quot;&gt;
        ///        &lt;script src=&quot;jquery-3.4.1.min.js&quot; charset=&quot;utf-8&quot;&gt;&lt;/script&gt;
        ///        &lt;tag autocomplete=&quot;off&quot; autocorrect=&quot;off&quot; autocapitalize=&quot;off&quot; spellcheck=&quot;false&quot;/&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; href=&quot;https://use.fontawesome.com/releases/v5.6.1/css/all.css&quot;&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; href=&quot;fontawsome.css&quot;&gt; &lt;!--this enabled when it can&apos;t access f[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ethernet_frame {
            get {
                return ResourceManager.GetString("ethernet_frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /*!
        /// * Font Awesome Free 5.6.1 by @fontawesome - https://fontawesome.com
        /// * License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
        /// */
        ///.fa,.fab,.fal,.far,.fas{-moz-osx-font-smoothing:grayscale;-webkit-font-smoothing:antialiased;display:inline-block;font-style:normal;font-variant:normal;text-rendering:auto;line-height:1}.fa-lg{font-size:1.33333em;line-height:.75em;vertical-align:-.0667em}.fa-xs{font-size:.75em}.fa-sm{font-size:.875em}.fa-1x{font-size:1em}[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string fontawsome {
            get {
                return ResourceManager.GetString("fontawsome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;kr&quot; &gt;
        ///    &lt;head&gt;
        ///        &lt;meta charset=&quot;utf-8&quot;&gt;
        ///        &lt;title&gt;&lt;/title&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; href=&quot;style_icmp.css&quot;&gt;
        ///        &lt;script src=&quot;jquery-3.4.1.min.js&quot; charset=&quot;utf-8&quot;&gt;&lt;/script&gt;
        ///        &lt;tag autocomplete=&quot;off&quot; autocorrect=&quot;off&quot; autocapitalize=&quot;off&quot; spellcheck=&quot;false&quot;/&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; href=&quot;https://use.fontawesome.com/releases/v5.6.1/css/all.css&quot;&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; href=&quot;fontawsome.css&quot;&gt; &lt;!--this enabled when it can&apos;t access fo[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string icmp_frame {
            get {
                return ResourceManager.GetString("icmp_frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;kr&quot; &gt;
        ///    &lt;head&gt;
        ///        &lt;meta charset=&quot;utf-8&quot;&gt;
        ///        &lt;title&gt;&lt;/title&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; href=&quot;style_ip.css&quot;&gt;
        ///        &lt;script src=&quot;jquery-3.4.1.min.js&quot; charset=&quot;utf-8&quot;&gt;&lt;/script&gt;
        ///        &lt;tag autocomplete=&quot;off&quot; autocorrect=&quot;off&quot; autocapitalize=&quot;off&quot; spellcheck=&quot;false&quot;/&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; href=&quot;https://use.fontawesome.com/releases/v5.6.1/css/all.css&quot;&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; href=&quot;fontawsome.css&quot;&gt; &lt;!--this enabled when it can&apos;t access font[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ip_frame {
            get {
                return ResourceManager.GetString("ip_frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /*! jQuery v3.4.1 | (c) JS Foundation and other contributors | jquery.org/license */
        ///!function(e,t){&quot;use strict&quot;;&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=e.document?t(e,!0):function(e){if(!e.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return t(e)}:t(e)}(&quot;undefined&quot;!=typeof window?window:this,function(C,e){&quot;use strict&quot;;var t=[],E=C.document,r=Object.getPrototypeOf,s=t.slice,g=t.concat,u=t.push,i=t.indexOf,n={},o=n.toString,v=n.hasOwnProperty,a=v.toStri[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jquery_3_4_1_min {
            get {
                return ResourceManager.GetString("jquery_3_4_1_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *{
        ///    margin: 0;
        ///    padding: 0;
        ///    text-decoration: none;
        ///    font-family: montserrat;
        ///    box-sizing: border-box;
        ///  }
        ///  body{
        ///    min-height: 1000px;
        ///    background-image: linear-gradient(120deg,#B3976F,#3498db);
        ///  }
        ///  .header{
        ///    position: static;
        ///    height: 100px;
        ///    background: #34495e;
        ///    padding: 0 20px;
        ///    color: #fff;
        ///  }
        ///  .arp-form{
        ///    width: 800px;
        ///    min-width: 400px;
        ///    background: #f1f1f1;
        ///    height: 700px;
        ///    min-height: 400px;
        ///    padding: 80px 40px;
        ///   [나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string style_arp {
            get {
                return ResourceManager.GetString("style_arp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *{
        ///    margin: 0;
        ///    padding: 0;
        ///    text-decoration: none;
        ///    font-family: montserrat;
        ///    box-sizing: border-box;
        ///  }
        ///  
        ///  body{
        ///    min-height: 1000px;
        ///    background-color: #3498db;
        ///  }
        ///  .header{
        ///    position: static;
        ///    height: 100px;
        ///    background: #34495e;
        ///    padding: 0 20px;
        ///    color: #fff;
        ///  }
        ///  .dns_frame{
        ///    width: 800px;
        ///    min-width: 400px;
        ///    background: #f1f1f1;
        ///    height: 700px;
        ///    min-height: 400px;
        ///    padding: 80px 40px;
        ///    border-radius: 10px;
        ///    [나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string style_dns {
            get {
                return ResourceManager.GetString("style_dns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *{
        ///    margin: 0;
        ///    padding: 0;
        ///    text-decoration: none;
        ///    font-family: montserrat;
        ///    box-sizing: border-box;
        ///  }
        ///  
        ///  body{
        ///    min-height: 1000px;
        ///    background-image: linear-gradient(120deg,#3498db,#8e44ad);
        ///  }
        ///.header{
        ///  position: static;
        ///  height: 80px;
        ///  background: #34495e;
        ///  padding: 0 20px;
        ///  color: #fff;
        ///}
        ///.ether_frame{
        ///  width: 360px;
        ///  background: #f1f1f1;
        ///  height: 750px;
        ///  padding: 80px 40px;
        ///  border-radius: 10px;
        ///  position: relative;
        ///  left: 50%;
        ///  top: [나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string style_ether {
            get {
                return ResourceManager.GetString("style_ether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *{
        ///    margin: 0;
        ///    padding: 0;
        ///    text-decoration: none;
        ///    font-family: montserrat;
        ///    box-sizing: border-box;
        ///  }
        ///  
        ///  body{
        ///    min-height: 1000px;
        ///    background-image: linear-gradient(120deg,#16a085,#f1c40f);
        ///  }
        ///  .header{
        ///    position: static;
        ///    height: 80px;
        ///    background: #34495e;
        ///    padding: 0 20px;
        ///    color: #fff;
        ///  }
        ///  .icmp_frame{
        ///    width: 800px;
        ///    min-width: 400px;
        ///    background: #f1f1f1;
        ///    height: 700px;
        ///    min-height: 400px;
        ///    padding: 80px 40px;[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string style_icmp {
            get {
                return ResourceManager.GetString("style_icmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *{
        ///    margin: 0;
        ///    padding: 0;
        ///    text-decoration: none;
        ///    font-family: montserrat;
        ///    box-sizing: border-box;
        ///  }
        ///  body{
        ///    min-height: 1000px;
        ///    background-image: linear-gradient(120deg,#2980b9,#27ae60);
        ///  }
        ///  .header{
        ///    position: static;
        ///    height: 100px;
        ///    background: #34495e;
        ///    padding: 0 20px;
        ///    color: #fff;
        ///  }
        ///  .ip_frame{
        ///    width: 800px;
        ///    min-width: 400px;
        ///    background: #f1f1f1;
        ///    height: 700px;
        ///    min-height: 400px;
        ///    padding: 80px 40px;
        ///   [나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string style_ip {
            get {
                return ResourceManager.GetString("style_ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *{
        ///    margin: 0;
        ///    padding: 0;
        ///    text-decoration: none;
        ///    font-family: montserrat;
        ///    box-sizing: border-box;
        ///  }
        ///  
        ///.logo{
        ///  line-height: 80px;
        ///  float: left;
        ///  text-transform: uppercase;
        ///}
        ///
        ///.menu{
        ///  float: right;
        ///  line-height: 80px;
        ///  font-family: &quot;montserrat&quot;,sans-serif;
        ///}
        ///.menu a{
        ///  color: #fff;
        ///  text-transform: uppercase;
        ///  text-decoration: none;
        ///  padding: 0 10px;
        ///  transition: 0.4s;
        ///  font-family: &quot;montserrat&quot;,sans-serif;
        ///}
        ///.menu a:hover
        ///{
        ///  color: #3498db;
        ///}
        ///[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string style_tcp {
            get {
                return ResourceManager.GetString("style_tcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *{
        ///    margin: 0;
        ///    padding: 0;
        ///    text-decoration: none;
        ///    font-family: montserrat;
        ///    box-sizing: border-box;
        ///  }
        ///  body{
        ///    min-height: 1000px;
        ///    background-image: linear-gradient(120deg,#1abc9c,#3498db);
        ///  }
        ///  .header{
        ///    position: static;
        ///    height: 100px;
        ///    background: #34495e;
        ///    padding: 0 20px;
        ///    color: #fff;
        ///  }
        ///  .udp-form{
        ///    width: 800px;
        ///    min-width: 400px;
        ///    background: #f1f1f1;
        ///    height: 700px;
        ///    min-height: 400px;
        ///    padding: 80px 40px;
        ///   [나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string style_udp {
            get {
                return ResourceManager.GetString("style_udp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;kr&quot; &gt;
        ///    &lt;head&gt;
        ///        &lt;meta charset=&quot;utf-8&quot;&gt;
        ///        &lt;title&gt;&lt;/title&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; href=&quot;style_tcp.css&quot;&gt;
        ///        &lt;script src=&quot;jquery-3.4.1.min.js&quot; charset=&quot;utf-8&quot;&gt;&lt;/script&gt;
        ///        &lt;tag autocomplete=&quot;off&quot; autocorrect=&quot;off&quot; autocapitalize=&quot;off&quot; spellcheck=&quot;false&quot;/&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; href=&quot;https://use.fontawesome.com/releases/v5.6.1/css/all.css&quot;&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; href=&quot;fontawsome.css&quot;&gt; &lt;!--this enabled when it can&apos;t access fon[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string tcp_frame {
            get {
                return ResourceManager.GetString("tcp_frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;kr&quot; &gt;
        ///    &lt;head&gt;
        ///        &lt;meta charset=&quot;utf-8&quot;&gt;
        ///        &lt;title&gt;&lt;/title&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; href=&quot;style_udp.css&quot;&gt;
        ///        &lt;script src=&quot;jquery-3.4.1.min.js&quot; charset=&quot;utf-8&quot;&gt;&lt;/script&gt;
        ///        &lt;tag autocomplete=&quot;off&quot; autocorrect=&quot;off&quot; autocapitalize=&quot;off&quot; spellcheck=&quot;false&quot;/&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; href=&quot;https://use.fontawesome.com/releases/v5.6.1/css/all.css&quot;&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; href=&quot;fontawsome.css&quot;&gt; &lt;!--this enabled when it can&apos;t access fon[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string udp_frame {
            get {
                return ResourceManager.GetString("udp_frame", resourceCulture);
            }
        }
    }
}
